default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 211011
  host: 127.0.0.1

development:
  <<: *default
  database: instagram_development

test:
  <<: *default
  database: instagram_test

production:
  <<: *default
  database: instagram_production
  username: instagram
  password: <%= ENV['INSTAGRAM_DATABASE_PASSWORD'] %>
